= Byteport HTTP APIv1

== Disclaimer
The Byteport HTTP APIv2 is under development with many additional functions.
The v1 API described in this document will be supported until 2016-12-31.

== Introduction
If you are not instructed otherwise, all calls should be made to the following URL

https://api.byteport.se

While it may work to access www.byteport.se for the same purpose, it may not be so in the future.

Whenever a GET-call is made, the client receives a cookie named csrftoken. This token must be supplied in all calls made below as csrftoken. In addition, the same token must be supplied as the form data parameter csrfmiddlewaretoken in any POST calls made. The csrftoken is a Cross Site Request Forgery token and is a security measure.

The client must then login correctly to obtain the sessionid cookie before any other service calls can be made. A HTTP POST call is made in this step.

Note that the responses given by the server is shown with a yellow background.

To be able to login and use the data accessing APIs you must have met the following prerequisites:

. Have a valid username and password to the Byteport instance you are accessing
. The user must have access to the namespace you are working against.
. Knowledge and understanding of the concepts namespace, device uid and field name etc.

== Storing data using API-key method

This method does not require the client to login to obtain the sessionid but instead you need to enable the namespace
to accept writes by API-key using either GET or POST methods, or both. See the namespace security-tab in the Byteport
instance (go here: https://www.byteport.se/manager/namespaces/, select namespace and open up “Security”).

=== Write

[cols="h,5a"]
|===

| URL
| /apiv1/store/

| Method(s)
| GET (2kB limit), POST (1 MB limit)

| Parameter(s)
| _key _ts [any other is interpreted as data field names]

| Response Body
| N/A

|===

=== Examples

==== Example 1
Storing a heartbeat using GET call, no data is supplied, that is supported:

`$ curl "http://api.byteport.se/apiv1/store/mySpace/10/?_key=1D3c2"`
